# Generated by Django 4.2.5 on 2023-10-12 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_nationalities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="players",
            name="nationality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.nationalities"
            ),
        ),
    ]
