# Generated by Django 4.2.5 on 2023-10-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_players_nationality"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPredictModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("label", models.CharField(default="data", max_length=20)),
            ],
        ),
    ]
